const firebaseConfig = {apiKey:'AIzaSyD8c4BOZcK8Ggn1APNRIeuoTSrQnAUxA9g',authDomain:'gaz-brigada.firebaseapp.com',projectId:'gaz-brigada',storageBucket:'gaz-brigada.firebasestorage.app',messagingSenderId:'708148971770',appId:'1:708148971770:web:8b11e06779cabb4038a143',measurementId:'G-QVFCL8P1P9'};
firebase.initializeApp(firebaseConfig);
const cloudAuth = firebase.auth();
const cloudDb = firebase.firestore();
const cloudDataRef = cloudDb.collection('appData').doc('production');
const cloudUsersRef = cloudDb.collection('users');
const adminEmail = 'egor.novoselisev@gmail.com';
const adminApp = firebase.initializeApp(firebaseConfig, 'admin-user-creator');
const adminAuth = adminApp.auth();
let cloudReady = false;
let cloudUser = null;
const blankCoordinates = [{point:'',system:'G54',x:'',y:'',z:'',b:''},{point:'',system:'G54',x:'',y:'',z:'',b:''}];
const defaultData = { machines: [], parts: [], defectRecords: [] };
const dataVersion = 'v4-clean';
let data;
try {
  if(localStorage.getItem('brigada-data-version') === dataVersion) data=JSON.parse(localStorage.getItem('brigada-data') || 'null') || JSON.parse(JSON.stringify(defaultData));
  else { localStorage.removeItem('brigada-data'); localStorage.removeItem('brigada-data-version'); data=JSON.parse(JSON.stringify(defaultData)); }
} catch { localStorage.removeItem('brigada-data'); localStorage.removeItem('brigada-data-version'); data=JSON.parse(JSON.stringify(defaultData)); }
data.defectRecords = Array.isArray(data.defectRecords) ? data.defectRecords : [];
data.users = data.users && typeof data.users === 'object' ? data.users : {};
let role = localStorage.getItem('brigada-role') || 'operator';
const $ = id => document.getElementById(id);
const machineById = id => data.machines.find(machine => machine.id === id);
const toolTypes = ['Фреза', 'Сверло', 'Метчик', 'Фасочник', 'Развёртка', 'Другой инструмент'];
function machineNumberValue(value){ const digits=String(value || '').replace(/\D/g,''); return digits ? Number(digits) : Number.MAX_SAFE_INTEGER; }
function formatMachineNumber(value){ const number=machineNumberValue(value); return Number.isFinite(number) && number !== Number.MAX_SAFE_INTEGER ? `№ ${String(number).padStart(2,'0')}` : String(value || '').trim(); }
function sortedMachines(){ return [...data.machines].sort((first,second)=>machineNumberValue(first.number)-machineNumberValue(second.number)); }
function machinesForPart(part){ const excluded=new Set(part.excludedMachineIds || []); return sortedMachines().filter(machine=>{ if(excluded.has(machine.id))return false; const config=part.machineConfigs?.[machine.id]; return Boolean(config?.program?.trim()) || (machine.id===part.machineId && Boolean(part.program?.trim())); }); }
function configFor(part,machineId){ const existing=part.machineConfigs?.[machineId]; if(existing)return existing; const source=part.machineConfigs?.[part.machineId] || {program:part.program,tools:part.tools,tool:part.tool,cell:part.cell}; if(machineId===part.machineId)return {...source,table1Fixture:part.table1Fixture,table2Fixture:part.table2Fixture,zero:part.zero,coordinates:part.coordinates}; return {program:machineById(machineId)?.program || '',tools:(source.tools || toolList(source)).map(tool=>({...tool})),tool:source.tool || '',cell:source.cell || '',table1Fixture:'',table2Fixture:'',zero:'G54 · X0.000 Y0.000 Z0.000',coordinates:blankCoordinates.map(coordinate=>({...coordinate}))}; }
function saveMachineConfig(part,machineId,config){ part.machineConfigs={...(part.machineConfigs || {}),[machineId]:config}; }
function activePart(part,machineId){ return {...part,...configFor(part,machineId),table1Fixture:part.table1Fixture || '',table2Fixture:part.table2Fixture || ''}; }
function formatToolDetail(value){ const detail=value.trim(); return /^\d+(?:[.,]\d+)?$/.test(detail) ? `Ø${detail.replace(',', '.')}` : detail; }
function toolList(part){ if(Array.isArray(part.tools)) return part.tools.map(tool=>({...tool,magazineCell:tool.magazineCell || tool.position || ''})); return (part.tool || '').split('\n').filter(Boolean).map(line=>{const match=line.match(/^(T\S+)\s*-\s*([^()]+)(?:\s*\((.*)\))?$/); return {position:match?.[1] || '',magazineCell:match?.[1] || '', type:toolTypes.find(type=>(match?.[2] || '').toLowerCase().includes(type.toLowerCase())) || 'Другой инструмент', detail:match?.[3] || match?.[2] || line};}); }
function addToolRow(tool={}){ const row=document.createElement('div'); row.className='tool-row'; row.innerHTML=`<input class="tool-position" required placeholder="T40" value="${tool.position || ''}"><select class="tool-type">${toolTypes.map(type=>`<option ${type===tool.type?'selected':''}>${type}</option>`).join('')}</select><input class="tool-detail" required placeholder="Диаметр / описание, например Ø32" value="${tool.detail || ''}"><input class="tool-cell" required placeholder="Ячейка T40" value="${tool.magazineCell || tool.position || ''}"><button type="button" class="remove-tool" title="Удалить инструмент">×</button>`; $('toolRows').appendChild(row); row.querySelector('.remove-tool').addEventListener('click',()=>{if($('toolRows').children.length>1)row.remove()}); }
function save(){ localStorage.setItem('brigada-data', JSON.stringify(data)); localStorage.setItem('brigada-data-version', dataVersion); if(cloudReady)cloudDataRef.set({machines:data.machines,parts:data.parts,defectRecords:data.defectRecords,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedBy:cloudUser?.email || ''}).catch(error=>toast(`Ошибка синхронизации: ${error.message}`)); }
async function loadCloudData(){ const snapshot=await cloudDataRef.get(); const usersSnapshot=await cloudUsersRef.get(); if(snapshot.exists){ const remote=snapshot.data(); data={machines:Array.isArray(remote.machines)?remote.machines:[],parts:Array.isArray(remote.parts)?remote.parts:[],defectRecords:Array.isArray(remote.defectRecords)?remote.defectRecords:[],users:{}}; } else await cloudDataRef.set({machines:data.machines,parts:data.parts,defectRecords:data.defectRecords,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedBy:cloudUser.email}); usersSnapshot.forEach(userDoc=>{data.users[userDoc.id]=userDoc.data();}); cloudReady=true; localStorage.setItem('brigada-data',JSON.stringify(data)); render(); }
function showAuth(message=''){ $('authView').classList.remove('hidden'); $('appShell').classList.add('hidden'); if(message)$('authMessage').textContent=message; }
function showApp(){ $('authView').classList.add('hidden'); $('appShell').classList.remove('hidden'); }
function authLogin(value){ const login=value.trim(); return /^\d{6}$/.test(login) ? `${login}@gezbrigada.local` : login; }
function generatedUserEmail(){ const code=$('userCode')?.value.trim() || ''; return /^\d{6}$/.test(code) ? `${code}@gezbrigada.local` : ''; }
function renderUsers(){ if(!$('userRows'))return; const users=Object.values(data.users || {}); $('userResultsLabel').textContent=`${users.length} ${users.length===1?'пользователь':'пользователей'}`; $('userRows').innerHTML=users.length ? users.map(user=>`<tr><td>${user.name || '—'}</td><td>${user.code}</td><td>${user.email}</td><td>${user.role==='setter'?'Наладчик':'Оператор'}</td><td>${user.active===false?'Отключён':'Активен'}</td></tr>`).join('') : '<tr><td colspan="5" class="empty-state">Пользователи ещё не добавлены</td></tr>'; }
function todayISO(){ return new Date().toISOString().slice(0,10); }
function defectPartOptions(){ return data.parts.map(part=>`<option value="${part.id}">${part.name} · ${part.code}</option>`).join(''); }
function updateDefectPartCode(){ const part=data.parts.find(item=>item.id===$('defectPart')?.value); if($('defectCode'))$('defectCode').value=part?.code || ''; }
function renderDefects(){ if(!$('defectPart'))return; const selected=$('defectPart').value; $('defectPart').innerHTML=defectPartOptions(); $('defectPart').value=data.parts.some(part=>part.id===selected) ? selected : data.parts[0]?.id || ''; updateDefectPartCode(); const records=[...data.defectRecords].sort((first,second)=>second.date.localeCompare(first.date)); $('defectResultsLabel').textContent=`${records.length} ${records.length===1?'запись':'записей'}`; $('defectRows').innerHTML=records.length ? records.map(record=>`<tr><td>${new Intl.DateTimeFormat('ru-RU').format(new Date(`${record.date}T00:00:00`))}</td><td>${record.partName}</td><td>${record.partCode}</td><td>${record.foundry}</td><td>${record.forging}</td><td>${record.mechanical}</td><td class="defect-explanation-cell">${record.explanation || '—'}</td><td class="defect-actions"><button type="button" class="icon-btn edit-defect-btn" data-defect-id="${record.id}">Изменить</button><button type="button" class="icon-btn delete-defect-btn" data-defect-id="${record.id}">Удалить</button></td></tr>`).join('') : '<tr><td colspan="8" class="empty-state">Записей пока нет</td></tr>'; }
function editDefect(record){ $('defectForm').dataset.editId=record.id; $('defectDate').value=record.date; $('defectPart').value=record.partId; updateDefectPartCode(); $('foundryDefect').value=record.foundry; $('forgingDefect').value=record.forging; $('mechanicalDefect').value=record.mechanical; $('defectExplanation').value=record.explanation || ''; $('defectSubmit').textContent='Сохранить изменения'; }
function resetDefectForm(){ delete $('defectForm').dataset.editId; $('defectDate').value=todayISO(); $('foundryDefect').value=0; $('forgingDefect').value=0; $('mechanicalDefect').value=0; $('defectExplanation').value=''; $('defectSubmit').textContent='＋ Добавить запись'; }
function render(){
  const query = $('searchInput').value.trim().toLowerCase(); const machine = $('machineFilter').value;
  const filtered = data.parts.filter(part => (!query || `${part.name} ${part.code}`.toLowerCase().includes(query)) && (machine === 'all' || part.machineId === machine));
  $('partsCount').textContent = data.parts.length; $('machinesCount').textContent = data.machines.length; $('statParts').textContent = data.parts.length; $('statMachines').textContent = data.machines.length; $('resultsLabel').textContent = `${filtered.length} ${filtered.length === 1 ? 'запись' : 'записей'}`;
  $('permissionHint').textContent = role === 'setter' ? 'Режим наладчика · полный доступ' : 'Режим оператора · просмотр'; $('avatar').textContent = role === 'setter' ? 'НЛ' : 'ОП'; document.querySelectorAll('.setter-only').forEach(el => el.classList.toggle('hidden', role !== 'setter'));
  $('partsGrid').innerHTML = filtered.length ? filtered.map(partCard).join('') : '<div class="empty-state">По вашему запросу ничего не найдено.</div>';
  const machines=sortedMachines(); const current = $('machineFilter').value; $('machineFilter').innerHTML = '<option value="all">Все станки</option>' + machines.map(m => `<option value="${m.id}">${m.number} · ${m.name}</option>`).join(''); $('machineFilter').value = data.machines.some(m => m.id === current) ? current : 'all';
  $('partMachine').innerHTML = machines.map(m => `<option value="${m.id}">${m.number} · ${m.name}</option>`).join(''); $('machineList').innerHTML = machines.map(m => `<article class="machine-row"><div><h3>${m.name}</h3><p>Станок ${m.number}</p></div>${role === 'setter' ? `<div class="card-actions"><button class="icon-btn edit-machine-btn" data-id="${m.id}">Изменить</button><button class="icon-btn delete-machine-btn" data-id="${m.id}">Удалить</button></div>` : ''}</article>`).join('');
  renderDefects();
  document.querySelectorAll('.admin-only').forEach(element=>element.classList.toggle('hidden',cloudUser?.email?.toLowerCase()!==adminEmail)); renderUsers();
}
function partCard(part){ return `<article class="part-card part-tile" data-open-part="${part.id}"><h3>${part.name}</h3><span class="part-code">${part.code}</span><span class="open-hint">Выбрать станок →</span>${role === 'operator' ? '' : `<div class="card-actions"><button class="icon-btn edit-btn" data-id="${part.id}">Изменить</button><button class="icon-btn delete-btn" data-id="${part.id}">Удалить</button></div>`}</article>`; }
let workflowPart; let workflowMode = 'quick'; let workflowStep = 0; let workflowMachineId = '';
const workflowSteps = [
  { title: 'Проверка приспособления', label: 'ПРИСПОСОБЛЕНИЕ', text: 'Проверьте номер приспособления, его установку и соответствие рабочему столу станка.', value: part => [part.table1Fixture,part.table2Fixture].map((fixture,index)=>fixtureValue(fixture,index)).filter(Boolean).join('') || '<span class="fixture-check-row"><strong>Приспособления не заданы</strong></span>' },
  { title: 'Проверка инструмента', label: 'ИНСТРУМЕНТ И ЯЧЕЙКИ', text: 'Убедитесь, что инструмент установлен в правильную ячейку и соответствует карте детали.', value: part => `${part.tool} · ${part.cell}` },
  { title: 'Замер инструмента', label: 'ИЗМЕРЕНИЕ', text: 'Выполните замер инструмента на станке и внесите полученные значения в таблицу коррекций.', value: part => `T${part.cell?.match(/\d+/)?.[0] || '04'} · длина 86.420 · радиус 6.000` },
  { title: 'Проверка нулевых координат', label: 'НУЛЬ ДЕТАЛИ', text: 'Проверьте привязку детали и убедитесь, что рабочий ноль соответствует карте запуска.', value: part => `<div class="coordinate-table setter-coordinate-grid">${coordinateRows(part)}</div>` }
];
function openWorkflow(part){ workflowPart=part; workflowMode='quick'; workflowStep=0; workflowMachineId=''; $('workflowBackdrop').classList.remove('hidden'); $('workflowTitle').textContent=part.name; $('workflowCode').textContent=part.code; const machines=machinesForPart(part); $('workflowMachines').innerHTML=machines.length ? machines.map(machine=>`<button type="button" class="machine-choice-btn" data-machine-id="${machine.id}"><strong>${machine.number}</strong><span>${machine.name}</span></button>`).join('') : '<div class="empty-state">Для этой детали пока нет станков с заполненной программой.</div>'; renderWorkflow(); }
function coordinateList(part){ if(Array.isArray(part.coordinates)) return part.coordinates.slice(0,2); return blankCoordinates.map(coordinate=>({...coordinate})); }
function hasFixture(value){ return String(value || '').trim() !== '' && String(value).trim() !== '0'; }
function fixtureValue(fixture,index){ return hasFixture(fixture) ? `<span class="fixture-check-row"><b>Стол ${index + 1}</b><strong>${fixture}</strong></span>` : ''; }
function coordinateRows(part){ return coordinateList(part).map((coordinate,index)=>({coordinate,index})).filter(item=>hasFixture(item.index ? part.table2Fixture : part.table1Fixture) && (item.coordinate.point || item.coordinate.x || item.coordinate.y || item.coordinate.z || item.coordinate.b)).map(item=>`<article class="coordinate-card"><header><strong>${item.coordinate.point || `P${String(item.index+13).padStart(3,'0')}`}</strong></header><div><span><em>X</em>${item.coordinate.x || '0.000'}</span><span><em>Y</em>${item.coordinate.y || '0.000'}</span><span><em>Z</em>${item.coordinate.z || '0.000'}</span><span><em>B</em>${item.coordinate.b || '0.000'}</span></div></article>`).join('') || '<div class="empty-state">Точки не заданы</div>'; }
function addCoordinateRow(coordinate={}){ const row=document.createElement('article'); row.className='coordinate-card coordinate-editor-card coordinate-editor-row'; row.dataset.coordinateIndex=coordinate.coordinateIndex ?? ''; row.innerHTML=`<header><label class="coordinate-point-field"><span>Название точки</span><input class="coordinate-point" placeholder="P013" value="${coordinate.point || ''}"></label><select class="coordinate-system" hidden><option selected>G54</option></select></header><div><label><em>X</em><input class="coordinate-x" placeholder="0.000" value="${coordinate.x || ''}"></label><label><em>Y</em><input class="coordinate-y" placeholder="0.000" value="${coordinate.y || ''}"></label><label><em>Z</em><input class="coordinate-z" placeholder="0.000" value="${coordinate.z || ''}"></label><label><em>B</em><input class="coordinate-b" placeholder="0.000" value="${coordinate.b || ''}"></label></div>`; $('coordinateRows').appendChild(row); }
function syncCoordinateRows(){ document.querySelectorAll('.coordinate-editor-row').forEach(row=>{ const index=Number(row.dataset.coordinateIndex); const fixture=index ? $('partTable2Fixture').value : $('partTable1Fixture').value; row.classList.toggle('hidden',!hasFixture(fixture)); }); }
function toolsMarkup(part){ return `<div class="tool-check-list">${toolList(part).map(tool=>`<div><strong>${tool.position}</strong><span>${tool.type}</span><b>${tool.detail}</b></div>`).join('')}</div>`; }
function measurementMarkup(part){ return `<label class="measurement-toggle"><input type="checkbox" id="measurementToggle"> Записать замер</label><div class="measurement-list hidden" id="measurementList">${toolList(part).map(tool=>`<div class="measurement-row"><strong>${tool.position}</strong><span>${tool.type} · ${tool.detail}</span><input placeholder="Длина"><input placeholder="Ширина"></div>`).join('')}</div>`; }
function renderWorkflow(){ const machineId=workflowMachineId; const machine=machineById(machineId); document.querySelectorAll('.machine-choice-btn').forEach(button=>button.classList.toggle('active',button.dataset.machineId===machineId)); document.querySelectorAll('.mode-card').forEach(button=>button.classList.toggle('active',button.dataset.mode===workflowMode)); if(!machineId){ $('workflowMachineInfo').innerHTML='<span>Выберите станок, чтобы открыть карту детали</span>'; $('workflowBody').innerHTML='<div class="empty-state">Данные детали появятся после выбора станка.</div>'; return; } const part=activePart(workflowPart,machineId); $('workflowMachineInfo').innerHTML=`<strong>${machine?.name || 'Станок не выбран'}</strong><span>Станок ${machine?.number || '—'} · данные карты детали</span>`; if(workflowMode==='quick'){ $('workflowBody').innerHTML=`<div class="quick-summary"><div class="quick-row"><span class="step-number">1</span><div><small>ПРОГРАММА</small><strong>Название программы</strong></div><b>${part.program || machine?.program || '—'}</b></div><div class="quick-row"><span class="step-number">2</span><div><small>ПРИСПОСОБЛЕНИЕ</small><strong>Столы детали</strong></div><b class="fixture-stack">Стол 1 · ${part.table1Fixture || 'Пусто'}<br>Стол 2 · ${part.table2Fixture || 'Пусто'}</b></div><div class="quick-row"><span class="step-number">3</span><div><small>ИНСТРУМЕНТЫ И ЯЧЕЙКИ</small><strong>Проверить по списку</strong></div><b class="tool-stack">${toolList(part).map(tool=>`${tool.position} · ${tool.type} · ${tool.detail}`).join('<br>') || 'Список пока не заполнен'}</b></div><div class="coordinate-block"><div class="quick-row"><span class="step-number">4</span><div><small>НУЛЕВЫЕ КООРДИНАТЫ</small></div></div><div class="coordinate-table">${coordinateRows(part)}</div></div></div>`; } else renderSetterWorkflow(); }
function renderSetterWorkflow(){ const step=workflowSteps[workflowStep]; const part=activePart(workflowPart,workflowMachineId); const progress=Math.round((workflowStep/workflowSteps.length)*100); const value=workflowStep===1 ? toolsMarkup(part) : workflowStep===2 ? measurementMarkup(part) : workflowStep===3 ? step.value(part) : `<strong>${step.value(part)}</strong>`; const valueLabel=workflowStep===3?'':'<span>По карте детали</span>'; $('workflowBody').innerHTML=`<div class="checklist-progress"><div><small>ШАГ ${workflowStep+1} ИЗ ${workflowSteps.length}</small><strong>${progress}% готово</strong></div><div class="progress-line"><span style="width:${progress}%"></span></div></div><div class="check-step"><div class="large-step-number">0${workflowStep+1}</div><div><small>${step.label}</small><h3>${step.title}</h3><p>${step.text}</p><div class="check-value"><span class="value-label">${valueLabel}</span>${value}</div><label class="confirm-check"><input type="checkbox" id="stepConfirmed"> Я проверил этот пункт</label></div></div><div class="workflow-actions"><button class="secondary-btn" id="backStep" ${workflowStep===0?'disabled':''}>← Назад</button><button class="primary-btn" id="nextStep">${workflowStep===workflowSteps.length-1?'Завершить наладку':'Далее →'}</button></div>`; }
function fillPartMachineConfig(part,machineId){ const config=activePart(part,machineId); $('partProgram').value=config.program || machineById(machineId)?.program || ''; $('partTable1Fixture').value=part.table1Fixture || ''; $('partTable2Fixture').value=part.table2Fixture || ''; $('toolRows').innerHTML=''; const tools=config.tools?.length ? config.tools : toolList(config); (tools.length ? tools : [{}]).forEach(addToolRow); $('coordinateRows').innerHTML=''; coordinateList(config).forEach((coordinate,index)=>{addCoordinateRow({...coordinate,coordinateIndex:index}); const row=$('coordinateRows').lastElementChild; row.classList.toggle('hidden',!hasFixture(index ? part.table2Fixture : part.table1Fixture));}); }
function openModal(part){ $('modalBackdrop').classList.remove('hidden'); $('modalTitle').textContent = part ? 'Изменить деталь' : 'Новая деталь'; $('partId').value = part?.id || ''; $('partName').value = part?.name || ''; $('partCode').value = part?.code || ''; $('partMachine').value = part?.machineId || data.machines[0]?.id || ''; fillPartMachineConfig(part || {},$('partMachine').value); document.querySelectorAll('#partForm input,#partForm select,#addToolBtn').forEach(el=>el.disabled=role === 'operator'); }
function openMachineModal(machine){ $('machineModalBackdrop').classList.remove('hidden'); $('machineModalTitle').textContent=machine?'Изменить станок':'Новый станок'; $('machineId').value=machine?.id||''; $('machineName').value=machine?.name||''; $('machineNumber').value=machine?.number||''; }
function closeModal(){ $('modalBackdrop').classList.add('hidden'); }
function toast(message){ $('toast').textContent=message; $('toast').classList.add('show'); setTimeout(()=>$('toast').classList.remove('show'),2400); }
$('roleSelect').value=role; $('today').textContent = new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date());
$('defectDate').value=todayISO(); $('defectPart').addEventListener('change',updateDefectPartCode); $('defectForm').addEventListener('submit',e=>{e.preventDefault(); const part=data.parts.find(item=>item.id===$('defectPart').value); if(!part)return; const values={date:$('defectDate').value,partId:part.id,partName:part.name,partCode:part.code,foundry:Number($('foundryDefect').value)||0,forging:Number($('forgingDefect').value)||0,mechanical:Number($('mechanicalDefect').value)||0,explanation:$('defectExplanation').value.trim()}; const editId=$('defectForm').dataset.editId; const record=data.defectRecords.find(item=>item.id===editId); if(record)Object.assign(record,values); else data.defectRecords.push({id:'d'+Date.now(),...values}); save(); renderDefects(); resetDefectForm(); toast(record?'Запись брака изменена':'Запись брака добавлена'); });
$('userCode').addEventListener('input',event=>{event.target.value=event.target.value.replace(/\D/g,'').slice(0,6); $('generatedUserEmail').value=generatedUserEmail();}); $('userForm').addEventListener('submit',async event=>{event.preventDefault(); if(cloudUser?.email?.toLowerCase()!==adminEmail){toast('Доступ только для администратора');return;} const code=$('userCode').value.trim(); const email=generatedUserEmail(); if(!/^\d{6}$/.test(code)){toast('Код должен состоять ровно из 6 цифр');return;} if(data.users[code]){toast('Такой код уже существует');return;} const button=event.target.querySelector('button'); button.disabled=true; try{const credential=await adminAuth.createUserWithEmailAndPassword(email,$('userPassword').value); const user={uid:credential.user.uid,name:$('userName').value.trim(),code,email,role:$('userRole').value,active:true}; await cloudUsersRef.doc(code).set(user); data.users[code]=user; await adminAuth.signOut(); renderUsers(); event.target.reset(); $('generatedUserEmail').value=''; toast('Пользователь создан');}catch(error){toast(error.code==='auth/email-already-in-use'?'Такой код уже зарегистрирован':'Не удалось создать пользователя');}finally{button.disabled=false;}});
$('roleSelect').addEventListener('change', e=>{ role=e.target.value; localStorage.setItem('brigada-role',role); render(); toast(role==='setter'?'Режим наладчика включён':'Режим оператора включён'); });
$('addPartBtn').addEventListener('click',()=>openModal()); $('closeModal').addEventListener('click',closeModal); $('cancelModal').addEventListener('click',closeModal); $('modalBackdrop').addEventListener('click',e=>{if(e.target===$('modalBackdrop'))closeModal()}); $('searchInput').addEventListener('input',render); $('machineFilter').addEventListener('change',render); $('clearSearch').addEventListener('click',()=>{$('searchInput').value='';$('machineFilter').value='all';render()});
$('addMachineBtn').addEventListener('click',()=>openMachineModal()); $('closeMachineModal').addEventListener('click',()=> $('machineModalBackdrop').classList.add('hidden')); $('cancelMachineModal').addEventListener('click',()=> $('machineModalBackdrop').classList.add('hidden')); $('machineModalBackdrop').addEventListener('click',e=>{if(e.target===$('machineModalBackdrop'))$('machineModalBackdrop').classList.add('hidden')}); $('machineNumber').addEventListener('blur',e=>{e.target.value=formatMachineNumber(e.target.value)}); $('machineForm').addEventListener('submit',e=>{e.preventDefault(); const id=$('machineId').value; const values={name:$('machineName').value.trim(),number:formatMachineNumber($('machineNumber').value)}; if(id)Object.assign(machineById(id),values); else data.machines.push({id:'m'+Date.now(),...values,program:''}); save();$('machineModalBackdrop').classList.add('hidden');render();toast(id?'Станок обновлён':'Станок добавлен');});
document.querySelectorAll('.nav-item').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(item=>item.classList.remove('active'));button.classList.add('active'); $('partsView').classList.toggle('hidden',button.dataset.view!=='parts'); $('machinesView').classList.toggle('hidden',button.dataset.view!=='machines'); $('statisticsView').classList.toggle('hidden',button.dataset.view!=='statistics'); $('defectsView').classList.toggle('hidden',button.dataset.view!=='defects'); $('adminView').classList.toggle('hidden',button.dataset.view!=='admin'); $('searchInput').closest('.toolbar').classList.toggle('hidden',button.dataset.view!=='parts'); if(button.dataset.view==='defects')renderDefects(); if(button.dataset.view==='admin')renderUsers();}));
document.addEventListener('click',e=>{ const defectId=e.target.dataset.defectId; if(defectId && e.target.classList.contains('edit-defect-btn')){const record=data.defectRecords.find(item=>item.id===defectId); if(record)editDefect(record); return;} if(defectId && e.target.classList.contains('delete-defect-btn')){if(confirm('Удалить эту запись брака?')){data.defectRecords=data.defectRecords.filter(item=>item.id!==defectId);save();renderDefects();toast('Запись брака удалена');} return;} const card=e.target.closest('[data-open-part]'); if(card && !e.target.closest('.card-actions'))openWorkflow(data.parts.find(item=>item.id===card.dataset.openPart)); const id=e.target.dataset.id; if(!id)return; const part=data.parts.find(item=>item.id===id); if(e.target.classList.contains('edit-machine-btn'))openMachineModal(machineById(id)); if(e.target.classList.contains('delete-machine-btn') && confirm('Удалить этот станок?')){data.machines=data.machines.filter(item=>item.id!==id);data.parts=data.parts.filter(item=>item.machineId!==id);save();render();toast('Станок удалён');} if(!part)return; if(e.target.classList.contains('edit-btn'))openModal(part); if(e.target.classList.contains('insert-btn')){const tool=prompt('Укажите новую пластинку / инструмент:',part.tool);if(tool && tool!==part.tool){part.tool=tool;save();render();toast('Пластинка обновлена');}} if(e.target.classList.contains('delete-btn') && confirm(`Удалить деталь «${part.name}»?`)){data.parts=data.parts.filter(item=>item.id!==id);save();render();toast('Деталь удалена');}});
$('closeWorkflow').addEventListener('click',()=> $('workflowBackdrop').classList.add('hidden')); $('workflowBackdrop').addEventListener('click',e=>{if(e.target===$('workflowBackdrop'))$('workflowBackdrop').classList.add('hidden');const machineButton=e.target.closest('.machine-choice-btn');if(machineButton){workflowMachineId=machineButton.dataset.machineId;renderWorkflow()}});
document.querySelectorAll('.mode-card').forEach(button=>button.addEventListener('click',()=>{workflowMode=button.dataset.mode;workflowStep=0;renderWorkflow()}));
document.addEventListener('click',e=>{if(e.target.id==='quickDone'){toast('Проверка завершена, станок готов к работе');$('workflowBackdrop').classList.add('hidden')} if(e.target.id==='backStep'){workflowStep=Math.max(0,workflowStep-1);renderWorkflow()} if(e.target.id==='nextStep'){if(!$('stepConfirmed')?.checked){toast('Подтвердите текущий пункт чеклиста');return} if(workflowStep===workflowSteps.length-1){toast('Наладка завершена, станок готов к работе');$('workflowBackdrop').classList.add('hidden')}else{workflowStep++;renderWorkflow()}}});
document.addEventListener('input',e=>{if(e.target.id==='partTable1Fixture' || e.target.id==='partTable2Fixture')syncCoordinateRows()}); document.addEventListener('change',e=>{if(e.target.id==='measurementToggle')$('measurementList').classList.toggle('hidden',!e.target.checked);if(e.target.id==='partMachine' && role==='setter'){const part=data.parts.find(item=>item.id===$('partId').value);fillPartMachineConfig(part || {},e.target.value)}if(e.target.id==='partTable1Fixture' || e.target.id==='partTable2Fixture')syncCoordinateRows()});
document.querySelector('.remove-part-machine').addEventListener('click',()=>{if(role!=='setter')return; const part=data.parts.find(item=>item.id===$('partId').value); const machineId=$('partMachine').value; if(!part || !machineId)return; if(!confirm(`Убрать станок ${machineById(machineId)?.number || ''} из детали?`))return; part.excludedMachineIds=[...(part.excludedMachineIds || []).filter(id=>id!==machineId),machineId]; delete part.machineConfigs?.[machineId]; if(part.machineId===machineId){const next=machinesForPart(part)[0]; part.machineId=next?.id || ''; if(!next){part.program='';part.tools=[];part.tool='';part.coordinates=[];part.zero='';}} save();render();openModal(part);toast('Станок убран из детали');}); $('addToolBtn').addEventListener('click',()=>addToolRow()); $('partForm').addEventListener('submit',e=>{e.preventDefault(); const id=$('partId').value; const tools=[...document.querySelectorAll('.tool-row')].map(row=>({position:row.querySelector('.tool-position').value.trim(),type:row.querySelector('.tool-type').value,detail:formatToolDetail(row.querySelector('.tool-detail').value),magazineCell:row.querySelector('.tool-cell').value.trim()})); const coordinates=[...document.querySelectorAll('.coordinate-editor-row')].map(row=>({point:row.querySelector('.coordinate-point').value.trim(),system:row.querySelector('.coordinate-system').value,x:row.querySelector('.coordinate-x').value.trim(),y:row.querySelector('.coordinate-y').value.trim(),z:row.querySelector('.coordinate-z').value.trim(),b:row.querySelector('.coordinate-b').value.trim()})); const first=coordinates[0] || {}; const machineId=$('partMachine').value; const machineConfig={program:$('partProgram').value.trim(),tools,tool:tools.map(item=>`${item.position} - ${item.type} (${item.detail})`).join('\n'),coordinates,zero:`${first.system || 'G54'} · X${first.x || '0.000'} Y${first.y || '0.000'} Z${first.z || '0.000'}`,cell:tools.map(item=>item.magazineCell).filter(Boolean).join('–')}; const values={name:$('partName').value.trim(),code:$('partCode').value.trim(),table1Fixture:$('partTable1Fixture').value.trim(),table2Fixture:$('partTable2Fixture').value.trim(),excludedMachineIds:(data.parts.find(p=>p.id===id)?.excludedMachineIds || []).filter(existingId=>existingId!==machineId)}; if(id){const part=data.parts.find(p=>p.id===id);Object.assign(part,values);saveMachineConfig(part,machineId,machineConfig)}else data.parts.push({id:'p'+Date.now(),...values,machineId,machineConfigs:{[machineId]:machineConfig}}); save();closeModal();render();toast(id?'Данные карты станка обновлены':'Деталь добавлена');});
$('resetData').addEventListener('click',()=>{if(confirm('Очистить общую базу? Это удалит детали, станки и журнал брака у всех пользователей.')){data=JSON.parse(JSON.stringify(defaultData));save();render();toast('Общая база очищена')}});
$('logoutBtn').addEventListener('click',()=>cloudAuth.signOut());
$('authForm').addEventListener('submit',async event=>{event.preventDefault(); const button=event.target.querySelector('button'); const login=$('authEmail').value.trim(); if(!/^\d{6}$/.test(login) && !/^\S+@\S+\.\S+$/.test(login)){ $('authMessage').textContent='Введите 6 цифр кода или корректный email.'; return; } button.disabled=true; $('authMessage').textContent='Выполняется вход...'; try{await cloudAuth.signInWithEmailAndPassword(authLogin(login),$('authPassword').value); $('authForm').reset();}catch(error){$('authMessage').textContent=error.code==='auth/invalid-credential'?'Неверный код или пароль.':'Не удалось войти. Проверьте данные и подключение.';}finally{button.disabled=false;}});
cloudAuth.onAuthStateChanged(async user=>{cloudUser=user; cloudReady=false; if(!user){showAuth();return;} $('authUser').textContent=user.email; showApp(); try{await loadCloudData();}catch(error){showAuth('Не удалось загрузить общую базу: проверьте настройки Firestore.'); toast('Ошибка подключения к Firestore');} });